/**
 * Tests for parsers/pdf.ts — PDF parsing (C1 parse completeness + determinism).
 *
 * TDD: These tests were written BEFORE the implementation.
 * Verifies:
 * - parsePdf returns text + pages for a real PDF
 * - pages array length matches actual page count
 * - metadata.totalPages matches pages.length
 * - text is the join of all pages (double newline)
 * - two runs return byte-identical extracted text (determinism)
 * - no page silently empty — empty pages ARE flagged but NOT dropped (C1)
 * - error path: throws for non-existent file
 */

import { describe, it, expect } from "vitest";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parsePdf } from "../pdf.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
// Minimal fixture PDF — generated by the test setup script
const fixturesDir = join(__dirname, "../../../../fixtures");
const samplePdf = join(fixturesDir, "sample.pdf");

describe("parsePdf — unit (sample fixture)", () => {
  it("returns RawParseResult with non-empty text", async () => {
    const result = await parsePdf(samplePdf);
    expect(result.text).toBeTruthy();
    expect(typeof result.text).toBe("string");
    expect(result.text.length).toBeGreaterThan(0);
  });

  it("returns pages array with length > 0", async () => {
    const result = await parsePdf(samplePdf);
    expect(Array.isArray(result.pages)).toBe(true);
    expect(result.pages.length).toBeGreaterThan(0);
  });

  it("metadata.totalPages equals pages.length", async () => {
    const result = await parsePdf(samplePdf);
    expect(result.metadata.totalPages).toBe(result.pages.length);
  });

  it("text equals pages joined with double newline", async () => {
    const result = await parsePdf(samplePdf);
    expect(result.text).toBe(result.pages.join("\n\n"));
  });

  it("two runs produce byte-identical text (determinism — C1)", async () => {
    const r1 = await parsePdf(samplePdf);
    const r2 = await parsePdf(samplePdf);
    expect(r1.text).toBe(r2.text);
    expect(r1.pages).toHaveLength(r2.pages.length);
    for (let i = 0; i < r1.pages.length; i++) {
      expect(r1.pages[i]).toBe(r2.pages[i]);
    }
  });

  it("all pages are strings (none silently dropped)", async () => {
    const result = await parsePdf(samplePdf);
    for (const page of result.pages) {
      expect(typeof page).toBe("string");
    }
  });

  it("metadata.parser is 'unpdf' or 'mupdf'", async () => {
    const result = await parsePdf(samplePdf);
    expect(["unpdf", "mupdf"]).toContain(result.metadata.parser);
  });
});

describe("parsePdf — error path", () => {
  it("throws descriptive error for non-existent file", async () => {
    await expect(parsePdf("/nonexistent/does-not-exist.pdf")).rejects.toThrow();
  });

  it("error message references the file path or PDF parse failure", async () => {
    await expect(parsePdf("/nonexistent/does-not-exist.pdf")).rejects.toThrow(
      /PDF|parse|ENOENT|nonexistent/i,
    );
  });
});
