import type { SysONElement } from '../types/sysml';

export interface TreeNode {
  element: SysONElement;
  children: TreeNode[];
}

const HIDDEN_TYPES = new Set([
  // Already-hidden metamodel relationship types
  'MembershipExpose',
  'FeatureTyping',
  'Subsetting',
  'Redefinition',
  'ReferenceSubsetting',
  'FeatureInverting',
  'TypeFeaturing',
  'ConjugatedPortDefinition',
  // Implicit KerML/SysML v2 structural elements generated by the compiler
  // (analogous to FeatureTyping — internal plumbing, never user-named)
  'ConjugatedPortTyping',
  'PortConjugation',
  'FeatureValue',
  'FeatureChaining',
  'Subclassification',
  'Conjugation',
  'Disjoining',
  'Unioning',
  'Intersecting',
  'Differencing',
  'NamespaceImport',
  'MembershipImport',
  'Annotation',
  'TextualRepresentation',
  // Expression and literal nodes (owned by AttributeUsages / FeatureValues — never standalone)
  'FeatureReferenceExpression',
  'FeatureChainExpression',
  'OperatorExpression',
  'InvocationExpression',
  'NullExpression',
  'LiteralBoolean',
  'LiteralInteger',
  'LiteralRational',
  'LiteralString',
  'LiteralInfinity',
  // Multiplicity and structural detail nodes
  'MultiplicityRange',
  'Multiplicity',
  // Flow / interface plumbing
  'FlowEnd',
  'PayloadFeature',
  // Raw unnamed KerML feature base types (appear as unnamed library nodes)
  'Feature',
  'SuccessionAsUsage',
  // Documentation is always a comment/annotation on another element, never standalone
  'Documentation',
  // RenderingUsage describes how a View renders its content — structural metadata, not a model element
  'RenderingUsage',
]);

// Types that are internal plumbing when unnamed but meaningful when user-declared
const HIDE_IF_UNNAMED = new Set([
  // Anonymous succession endpoints hoisted from hidden SuccessionAsUsage nodes
  'ReferenceUsage',
  // Anonymous requirement/constraint relationships — only meaningful if explicitly named
  'SatisfyRequirementUsage',
  'AssertConstraintUsage',
]);

// Container types that are meaningful even if unnamed (e.g., a root Namespace)
const CONTAINER_TYPES = new Set([
  'Package', 'Namespace', 'LibraryPackage',
]);

function hasUserName(el: SysONElement): boolean {
  return !!(el.declaredName || el.name);
}

function isHidden(type: string, el?: SysONElement): boolean {
  if (type.endsWith('Membership') || HIDDEN_TYPES.has(type)) return true;
  if (el && HIDE_IF_UNNAMED.has(type) && !hasUserName(el)) return true;
  return false;
}

export function buildContainmentTree(elements: SysONElement[]): TreeNode[] {
  const byId = new Map<string, SysONElement>();
  for (const el of elements) byId.set(el['@id'], el);

  const childrenOf = new Map<string, SysONElement[]>();
  for (const el of elements) {
    const ownerId = el.owner?.['@id'];
    if (!ownerId) continue;
    if (!childrenOf.has(ownerId)) childrenOf.set(ownerId, []);
    childrenOf.get(ownerId)!.push(el);
  }

  function buildNode(el: SysONElement): TreeNode | null {
    if (isHidden(el['@type'], el)) return null;
    const directChildren = childrenOf.get(el['@id']) ?? [];
    const logicalChildren: TreeNode[] = [];
    for (const child of directChildren) {
      if (isHidden(child['@type'], child)) {
        // Hoist grandchildren of hidden nodes so they appear under the visible parent
        const grandchildren = childrenOf.get(child['@id']) ?? [];
        for (const gc of grandchildren) {
          const node = buildNode(gc);
          if (node) logicalChildren.push(node);
        }
      } else {
        const node = buildNode(child);
        if (node) logicalChildren.push(node);
      }
    }
    return { element: el, children: logicalChildren };
  }

  // An element is eligible as a root only if it's not hidden AND either:
  //  (a) it has a user-declared name, OR
  //  (b) it is a container type (Package/Namespace) — those are meaningful even unnamed
  function isRootEligible(el: SysONElement): boolean {
    if (isHidden(el['@type'], el)) return false;
    return hasUserName(el) || CONTAINER_TYPES.has(el['@type']);
  }

  const roots: TreeNode[] = [];
  for (const el of elements) {
    if (el.owner === null || el.owner === undefined) {
      if (isRootEligible(el)) {
        const node = buildNode(el);
        if (node) roots.push(node);
      }
    }
  }

  if (roots.length === 0) {
    for (const el of elements) {
      const ownerId = el.owner?.['@id'];
      if (ownerId && !byId.has(ownerId) && isRootEligible(el)) {
        const node = buildNode(el);
        if (node) roots.push(node);
      }
    }
  }

  return roots;
}
